name: CoderCo Combined

on:   
 push:
    branches:
      - main


jobs: 
    build: 
        runs-on: ubuntu-latest

        strategy:
          matrix: 
            python-version: [3.7, 3.8, 3.9]

        steps:
        - name: checkout code
          uses: actions/checkout@v2

        - name: setup Python
          uses: actions/setup-python@v2
          with: 
            python-version: ${{ matrix.python-version }}

        - name: this is our little secret 
          run: echo "pssst this is the secret ---> $MY_SECRET_NAME"
          env:
            MY_SECRET_NAME: ${{ secrets.MY_SECRET_NAME }}

        - name: install dependencies
          run: |
            cd cicd1/.github/Chapter4
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: run tests
          run: |
            cd cicd1/.github/Chapter4
            python -m unittest discover
          
        
        - name: notify us of success
          run: echo "This application, under Python ${{ matrix.python-version }} is actually working"