name: CoderCo First CICD Workflow

on: [push]

jobs:
    build: 
      runs-on: ubuntu-latest
      steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: This is a test
        run: echo Hello People!!!